# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ColorBookmark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ColorBookmark
  pod 'MaterialComponents/BottomSheet'
  pod 'FloatingPanel'
  pod 'Alamofire', '~> 5.4'
  pod 'KakaoSDK'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'YPImagePicker'
end
