# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CMC-IOS-ColorBookmark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CMC-IOS-ColorBookmark
pod 'MaterialComponents/BottomSheet'
end
